import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Download, Save, FileText, User, Calendar } from "lucide-react";
import { useMedoraStore } from "@/stores/medoraStore";
import { mockRecords } from "@/mocks/seeds";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/hooks/useFirebase";
import { doc, getDoc } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { useState, useEffect } from 'react';

export const PreviewModal = () => {
  const { 
    showPreview, 
    setShowPreview, 
    soapNote, 
    currentPatient 
  } = useMedoraStore();
  const { toast } = useToast();
  const { user } = useAuth();
  const [doctorName, setDoctorName] = useState('Dr. Smith');

  // Fetch doctor name from Firestore
  useEffect(() => {
    const fetchDoctorName = async () => {
      if (user) {
        try {
          const userDocRef = doc(db, 'doctors', user.uid);
          const userDoc = await getDoc(userDocRef);
          
          if (userDoc.exists()) {
            const data = userDoc.data();
            setDoctorName(data.displayName || user.displayName || 'Dr. Smith');
          } else {
            setDoctorName(user.displayName || user.email?.split('@')[0] || 'Dr. Smith');
          }
        } catch (error) {
          console.error('Error fetching doctor name:', error);
          setDoctorName(user.displayName || user.email?.split('@')[0] || 'Dr. Smith');
        }
      }
    };

    fetchDoctorName();
  }, [user]);

  const exportSOAP = () => {
    if (!currentPatient) return;

    const patientName = currentPatient.pet?.name || currentPatient.name || 'Unknown';
    const patientMRN = currentPatient.mrn || 'N/A';
    const species = currentPatient.pet?.species || 'Unknown';
    const breed = currentPatient.pet?.breed || 'Unknown';
    const age = currentPatient.pet?.age || currentPatient.age || 'Unknown';
    const weight = currentPatient.pet?.weight ? `${currentPatient.pet.weight} kg` : 'Unknown';
    const ownerName = currentPatient.owner?.name || 'Unknown';

    const soapContent = `
SOAP NOTE - ${patientName} (MRN: ${patientMRN})
Date: ${new Date().toLocaleDateString()}
Generated by Medora v0.2.0

PATIENT INFORMATION:
Pet Name: ${patientName}
Species: ${species}
Breed: ${breed}
Age: ${age} years
Weight: ${weight}
Owner: ${ownerName}

SUBJECTIVE:
${soapNote.subjective || 'Not documented'}

OBJECTIVE:
${soapNote.objective || 'Not documented'}

ASSESSMENT:
${soapNote.assessment || 'Not documented'}

PLAN:
${soapNote.plan || 'Not documented'}

---
This is a demonstration SOAP note generated by Medora.
Not for actual medical use.
    `.trim();

    // Create blob and download
    const blob = new Blob([soapContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `soap-note-${patientName.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Exported SOAP Note",
      description: "SOAP note has been exported successfully.",
    });
  };

  const saveSOAP = () => {
    if (!currentPatient || !user) return;

    const soapRecord = {
      id: `soap-${Date.now()}`,
      patientId: currentPatient.id,
      petId: currentPatient.id, // Tag to pet (using patient ID as pet ID in this structure)
      doctorId: user.uid, // Tag to doctor (Firebase Auth UID)
      doctorName: doctorName, // Doctor name for display
      date: new Date().toISOString(),
      subjective: soapNote.subjective,
      objective: soapNote.objective,
      assessment: soapNote.assessment,
      plan: soapNote.plan
    };

    mockRecords.save(currentPatient.id, soapRecord);
    
    toast({
      title: "SOAP Note Saved",
      description: `Note saved and tagged to ${currentPatient.pet?.name || currentPatient.name} and ${doctorName}.`,
    });
    
    setShowPreview(false);
  };

  const isComplete = Object.values(soapNote).every(section => {
    const sectionStr = typeof section === 'string' ? section : String(section || '');
    return sectionStr.trim().length > 0;
  });
  const wordCount = Object.values(soapNote).reduce((total, section) => {
    const sectionStr = typeof section === 'string' ? section : String(section || '');
    return total + (sectionStr.trim() ? sectionStr.trim().split(/\s+/).length : 0);
  }, 0);

  return (
    <Dialog open={showPreview} onOpenChange={setShowPreview}>
      <DialogContent className="max-w-4xl max-h-[90vh]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-medical-primary" />
            SOAP Note Preview
            <Badge variant={isComplete ? "default" : "secondary"}>
              {isComplete ? "Complete" : "Incomplete"}
            </Badge>
            <Badge variant="outline">
              {wordCount} words
            </Badge>
          </DialogTitle>
        </DialogHeader>

        <ScrollArea className="max-h-[60vh]">
          <div className="space-y-6 pr-4">
            {/* Patient Info */}
            {currentPatient && (
              <div className="bg-secondary/50 p-4 rounded-lg">
                <div className="flex items-center gap-4">
                  <User className="h-5 w-5 text-muted-foreground" />
                  <div>
                    <h3 className="font-semibold">
                      {currentPatient.pet?.name || currentPatient.name || 'Unknown Patient'}
                    </h3>
                    <p className="text-sm text-muted-foreground">
                      {currentPatient.pet?.species && (
                        <>
                          {currentPatient.pet.species} • {currentPatient.pet.breed || 'Unknown breed'} • 
                        </>
                      )}
                      MRN: {currentPatient.mrn || 'N/A'} • 
                      Age: {currentPatient.pet?.age || currentPatient.age || 'Unknown'} years
                      {currentPatient.pet?.weight && ` • Weight: ${currentPatient.pet.weight} kg`}
                    </p>
                    {currentPatient.owner?.name && (
                      <p className="text-xs text-muted-foreground mt-1">
                        Owner: {currentPatient.owner.name}
                      </p>
                    )}
                    <p className="text-xs text-muted-foreground mt-1">
                      Consulted by: {doctorName}
                    </p>
                  </div>
                  <div className="ml-auto flex items-center gap-2">
                    <Calendar className="h-4 w-4 text-muted-foreground" />
                    <span className="text-sm text-muted-foreground">
                      {new Date().toLocaleDateString()}
                    </span>
                  </div>
                </div>
              </div>
            )}

            {/* SOAP Sections */}
            <div className="space-y-4">
              <div>
                <h4 className="font-semibold text-medical-primary mb-2">SUBJECTIVE</h4>
                <div className="bg-muted/50 p-4 rounded-lg">
                  <p className="text-sm leading-relaxed whitespace-pre-wrap">
                    {soapNote.subjective || <em className="text-muted-foreground">Not documented</em>}
                  </p>
                </div>
              </div>

              <Separator />

              <div>
                <h4 className="font-semibold text-medical-primary mb-2">OBJECTIVE</h4>
                <div className="bg-muted/50 p-4 rounded-lg">
                  <p className="text-sm leading-relaxed whitespace-pre-wrap">
                    {soapNote.objective || <em className="text-muted-foreground">Not documented</em>}
                  </p>
                </div>
              </div>

              <Separator />

              <div>
                <h4 className="font-semibold text-medical-primary mb-2">ASSESSMENT</h4>
                <div className="bg-muted/50 p-4 rounded-lg">
                  <p className="text-sm leading-relaxed whitespace-pre-wrap">
                    {soapNote.assessment || <em className="text-muted-foreground">Not documented</em>}
                  </p>
                </div>
              </div>

              <Separator />

              <div>
                <h4 className="font-semibold text-medical-primary mb-2">PLAN</h4>
                <div className="bg-muted/50 p-4 rounded-lg">
                  <p className="text-sm leading-relaxed whitespace-pre-wrap">
                    {soapNote.plan || <em className="text-muted-foreground">Not documented</em>}
                  </p>
                </div>
              </div>
            </div>

            {/* Disclaimer */}
            <div className="bg-medical-warning/10 border border-medical-warning/20 p-4 rounded-lg">
              <p className="text-xs text-muted-foreground">
                <strong>Demo Disclaimer:</strong> This SOAP note was generated by Medora v0.2.0 
                for demonstration purposes only. Not intended for actual medical use.
              </p>
            </div>
          </div>
        </ScrollArea>

        <DialogFooter className="gap-2">
          <Button variant="outline" onClick={() => setShowPreview(false)}>
            Close
          </Button>
          <Button 
            variant="outline" 
            onClick={exportSOAP}
            className="gap-2"
            disabled={wordCount === 0}
          >
            <Download className="h-4 w-4" />
            Export
          </Button>
          <Button 
            onClick={saveSOAP}
            className="gap-2"
            disabled={wordCount === 0}
          >
            <Save className="h-4 w-4" />
            Save Note
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};